baseurl = "https://example.com"
languageCode = "en-US"
title = "[Hu]Core"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">[Hu]Core theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "shortname"
googleAnalytics = "trackingcode"
languageCode = "en-EN"
metaDataFormat = "yaml"
theme = "hucore"
paginate = 10
paginatePath = "page"

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Morten Johansen"
sharingicons = true

[params.highlight]
style = "github"
languages = ["scala", "python"]

[[params.social]]
url = "https://github.com/ritchie46"
fa_icon = "fa-github"

[[params.social]]
url = "https://linkedin.com/in/ritchievink/"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/ritchievink"
fa_icon = "fa-linkedin-square"

[[params.static_pages]]
url = "/about/"
tag = "about"

[[params.static_pages]]
url = "/anastruct/"
tag = "anastruct"

[[params.static_pages]]
url = "/mnkappa/"
tag = "m-n-kappa"
